---
global:
  cloudHsm:
    enabled: true
    ip: "10.255.151.206"

httpsEgressSafelist:
- name: stub-connector
  fqdn: test-connector.london.verify.govsvc.uk
- name: hub-integration
  fqdn: www.integration.signin.service.gov.uk
- name: test-intgegration
  fqdn: test-integration-connector.london.verify.govsvc.uk
- name: nl-integration
  fqdn: acc-eidas.minez.nl
- name: dk-integration
  fqdn: eidasconnector.test.eid.digst.dk
- name: hub-prod
  fqdn: www.signin.service.gov.uk
- name: nl-prod
  fqdn: eidas.minez.nl
- name: dk-prod
  fqdn: eidasconnector.eid.digst.dk
- name: sqs-eu-west-2
  fqdn: sqs.eu-west-2.amazonaws.com

namespaces:
- name: verify-main

- name: verify-connector-node-metadata
  owner: alphagov
  repository: verify-metadata
  branch: master
  path: ci/verify
  requiredApprovalCount: 2

- name: verify-metadata-controller
  owner: alphagov
  repository: verify-metadata-controller
  branch: master
  path: ci/verify
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
  scope: cluster

- name: verify-proxy-node-build
  owner: alphagov
  repository: verify-proxy-node
  path: ci/build
  requiredApprovalCount: 2
- name: verify-proxy-node-integration
  owner: alphagov
  repository: verify-proxy-node
  path: ci/integration
  requiredApprovalCount: 2
- name: verify-proxy-node-prod
  owner: alphagov
  repository: verify-proxy-node
  path: ci/prod
  requiredApprovalCount: 2

# legacy; needs to be deleted carefully
- name: doc-checking-staging
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/staging
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
- name: doc-checking-test
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/test
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
- name: doc-checking-prod
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/prod
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2

- name: verify-doc-checking-staging
  owner: alphagov
  repository: doc-checking
  branch: OGD-253/make-pipeline-push-to-harbour
  path: ci/staging
  permittedRolesRegex: "^$"
  requiredApprovalCount: 0
- name: verify-doc-checking-test
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/test
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
- name: verify-doc-checking-prod
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/prod
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
- name: verify-doc-checking-build
  owner: alphagov
  repository: doc-checking
  branch: OGD-253/make-pipeline-push-to-harbour
  path: ci/build
  permittedRolesRegex: "^$"
  requiredApprovalCount: 0
