---
global:
  cloudHsm:
    enabled: true
    ip: "10.255.151.206"

httpsEgressSafelist:
- name: proxy-node-test
  fqdn: test-proxy-node.london.verify.govsvc.uk
- name: stub-connector
  fqdn: test-connector.london.verify.govsvc.uk
- name: hub-integration
  fqdn: www.integration.signin.service.gov.uk
- name: nl-integration
  fqdn: acc-eidas.minez.nl
- name: dk-integration
  fqdn: eidasconnector.test.eid.digst.dk
- name: hub-prod
  fqdn: www.signin.service.gov.uk
- name: nl-prod
  fqdn: eidas.minez.nl
- name: dk-prod
  fqdn: eidasconnector.eid.digst.dk

namespaces:
- name: verify-main
- name: verify-metadata-controller
  owner: alphagov
  repository: verify-metadata-controller
  branch: master
  path: ci
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
  scope: cluster
- name: verify-proxy-node-build
  owner: alphagov
  repository: verify-proxy-node
  path: ci/build
  requiredApprovalCount: 2
- name: verify-proxy-node-integration
  owner: alphagov
  repository: verify-proxy-node
  path: ci/integration
  requiredApprovalCount: 2
- name: verify-proxy-node-prod
  owner: alphagov
  repository: verify-proxy-node
  path: ci/prod
  requiredApprovalCount: 2
