---
global:
  cloudHsm:
    enabled: true
    ip: "10.255.151.206"

# whitelist of services external from the cluster
# that we allow egress traffic to.
# see https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/#ServiceEntry
# for the format of the `service` block
egressSafelist:
- name: proxy-node-build
  service:
    hosts:
      # Stub Connector build
      - stub-connector.test.verify-eidas-proxy-node-build.london.verify.govsvc.uk
      - stub-connector.test.eidas.signin.service.gov.uk
      # Hub integration
      - www.integration.signin.service.gov.uk
    ports:
      - name: https
        number: 443
        protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS

- name: proxy-node-integration
  service:
    hosts:
      # Stub Connector
      - stub-connector.integration.verify-eidas-proxy-node-deploy.london.verify.govsvc.uk
      - stub-connector.integration.eidas.signin.service.gov.uk
      # Hub integration
      - www.integration.signin.service.gov.uk
      # HMRC integration
      - hmrc-integration-connector.london.verify.govsvc.uk
      - test-www.tax.service.gov.uk
      # European Commission
      - ec.europa.eu
      # Austria
      - eidas-test.bmi.gv.at
      # Belgium
      - idp.iamfas.qa.belgium.be
      # Bulgaria
      - eidas-test.egov.bg
      # Croatia
      - eidastst.fina.hr
      # Cyprus
      - pre-eidas.mof.gov.cy
      # Czech Republic
      - conn.dev.eidasnode.cz
      # Denmark
      - eidasconnector.test.eid.digst.dk
      # Estonia
      - eidastest.eesti.ee
      # Finland
      - nodefi1.apro.tunnistus.fi
      # France
      - fc-node.eidas.integ01.dev-franceconnect.fr
      # Greece
      - pre.eidas.gov.gr
      # Hungary
      - hpeps.teszt.gov.hu
      # Iceland
      - testnode.island.is
      # Ireland
      - demo.eidasnode.gov.ie
      # Italy
      - connector.pre.eid.gov.it
      # Latvia
      - eidastest.vraa.gov.lv
      # Lithuania
      - testpeps.eid.lt
      # Luxembourg
      - eidas-test.services-publics.lu
      # Malta
      - stgmteidasnode.gov.mt
      # Netherlands
      - acc-eidas.minez.nl
      # Norway
      - eidas-test1.difi.eon.no
      # Poland
      - test.eidas.gov.pl
      # Portugal
      - preprod.eidas.autenticacao.gov.pt
      # Slovakia
      - eidas.upvsfixnew.gov.sk
      # Slovenia
      - sipeps-test.gov.si
      # Spain
      - se-eidas.redsara.es
      # Sweden
      - qa.connector.eidas.swedenconnect.se
    ports:
    - name: https
      number: 443
      protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS

- name: proxy-node-production
  service:
    hosts:
      # Hub production
      - www.signin.service.gov.uk
      # Netherlands
      - eidas.minez.nl
      # Denmark
      - eidasconnector.eid.digst.dk
      # Sweden
      - connector.eidas.swedenconnect.se
      # Czechia
      - conn.eidasnode.cz
      # Italy
      - connector.eid.gov.it
      # Malta
      - mteidasnode.gov.mt
      # Estonia
      - eidas.ria.ee
      # Spain
      - eidas.redsara.es
      # Slovakia
      - eidas.slovensko.sk

    ports:
    - name: https
      number: 443
      protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS

- name: sqs-eu-west-2
  service:
    hosts: ["sqs.eu-west-2.amazonaws.com", "eu-west-2.queue.amazonaws.com"]
    ports:
    - name: https
      number: 443
      protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS
- name: ocsp
  service:
    hosts: ["std-ocsp.trustwise.com"]
    ports:
    - name: http
      number: 80
      protocol: HTTP
    location: MESH_EXTERNAL
    resolution: DNS

namespaces:
- name: verify-main
  ingress:
    enabled: true

# Connector Node namespaces

- name: verify-connector-node-metadata
  owner: alphagov
  repository: verify-metadata
  branch: master
  path: ci/verify
  requiredApprovalCount: 2
  ingress:
    enabled: true

# Proxy Node namespaces
- name: verify-eidas-proxy-node-build
  owner: alphagov
  repository: verify-proxy-node
  branch: master
  path: ci/build
  requiredApprovalCount: 2
  talksToHsm: true
  ingress:
    enabled: true

# Proxy Node namespace for both the integration and production release
- name: verify-eidas-proxy-node-deploy
  owner: alphagov
  repository: verify-proxy-node
  branch: master
  path: ci/deploy
  requiredApprovalCount: 2
  talksToHsm: true
  ingress:
    enabled: true

# Verify Metadata Controller (VMC) namespace
- name: verify-metadata-controller
  owner: alphagov
  repository: verify-metadata-controller
  branch: master
  path: ci/verify
  requiredApprovalCount: 2
  scope: cluster
  talksToHsm: true

# DCS namespaces
- name: verify-doc-checking-prod
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/prod
  requiredApprovalCount: 1
  talksToPsn: true
  ingress:
    enabled: true
- name: verify-doc-checking-build
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/build
  requiredApprovalCount: 1
  ingress:
    enabled: true
- name: verify-dcs-integration
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/integration
  requiredApprovalCount: 1
  ingress:
    enabled: true
- name: verify-doc-checking-sandbox

extraPermissionsSRE:
  - apiGroups: ["verify.gov.uk"]
    resources: ["certificaterequests", "metadata"]
    verbs:
    - get
    - list
    - watch
extraPermissionsDev:
  - apiGroups: ["verify.gov.uk"]
    resources: ["certificaterequests", "metadata"]
    verbs:
    - get
    - list
    - watch
