---
global:
  cloudHsm:
    enabled: true
    ip: "10.255.151.206"

httpsEgressSafelist:
- name: hub
  fqdn: www.integration.signin.service.gov.uk
- name: nl
  fqdn: acc-eidas.minez.nl
- name: dk
  fqdn: eidasconnector.test.eid.digst.dk
- name: stub-connector
  fqdn: test-connector-metadata.london.verify.govsvc.uk

namespaces:
- name: verify-main

- name: verify-metadata-controller
  owner: alphagov
  repository: verify-metadata-controller
  branch: master
  path: ci
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
  scope: cluster

- name: verify-proxy-node-build
  owner: alphagov
  repository: verify-proxy-node
  path: ci/build
  requiredApprovalCount: 2
- name: verify-proxy-node-integration
  owner: alphagov
  repository: verify-proxy-node
  path: ci/integration
  requiredApprovalCount: 2
- name: verify-proxy-node-prod
  owner: alphagov
  repository: verify-proxy-node
  path: ci/prod
  requiredApprovalCount: 2

- name: doc-checking-staging
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/staging
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
- name: doc-checking-test
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/test
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
- name: doc-checking-prod
  owner: alphagov
  repository: doc-checking
  branch: master
  path: ci/prod
  permittedRolesRegex: "^$"
  requiredApprovalCount: 2
